runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /other
  static_dir: other

- url: /.*
  script: home.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest